/* ── Assembly & Profile ───────────────────────────────────── */

export const ASSEMBLY_DETAILS = {
  assemblyNo: 141,
  assemblyName: "Dhone",
  assemblyNameTelugu: "డోన్",
  category: "GEN",
  state: "Andhra Pradesh",
  stateCode: "S01",
  district: "Nandyal",
  districtTelugu: "నంద్యాల",
  districtCode: "S0120",
  parliamentName: "నంద్యాల (Nandyal)",
  parliamentCategory: "General",
  historicalName: "Dronachalam",
  historicalOrigin:
    "Named after the legendary guru Dronacharya from the Mahabharata",
  municipalArea: "9.85 km²",
  municipalWards: 32,
  upgradedToMunicipality: 2005,
  revenueDivisions: 4,
} as const;

export const PROFILE = {
  economy:
    "Globally recognized for its massive limestone deposits, leading to a booming local stone crushing and mining industry.",
  connectivity:
    "Houses a major railway junction connecting northern and southern India, positioned strategically right along National Highway 44 (NH44).",
  administration:
    "Upgraded to a Municipality in 2005, spanning an area of 9.85 km² and divided into 32 municipal wards. One of 4 revenue divisions in Nandyal district.",
  pinCode: "518222",
  nearestTown: "Nandyal (~65 km)",
  rivers: "Kunderu River",
  heritage:
    "Bethamcherla limestone quarries — among the largest in Asia; Dhone Junction railway station (est. 1871)",
} as const;

/* ── Mandal-level data (Census 2011) ─────────────────────── */

export type MandalData = {
  name: string;
  slug: string;
  villages: number;
  gramPanchayats: number;
  population: number;
  male: number;
  female: number;
  households: number;
  sexRatio: number;
  scPopulation: number;
  stPopulation: number;
  scPercent: number;
  stPercent: number;
  literacy: number;
  area: number;
  density: number;
};

export const MANDALS: MandalData[] = [
  {
    name: "Dhone",
    slug: "dhone",
    villages: 16,
    gramPanchayats: 25,
    population: 120232,
    male: 60558,
    female: 59674,
    households: 26505,
    sexRatio: 985,
    scPopulation: 16613,
    stPopulation: 3064,
    scPercent: 13.82,
    stPercent: 2.55,
    literacy: 55.41,
    area: 563,
    density: 214,
  },
  {
    name: "Bethamcherla",
    slug: "bethamcherla",
    villages: 10,
    gramPanchayats: 20,
    population: 88726,
    male: 44426,
    female: 44300,
    households: 20828,
    sexRatio: 997,
    scPopulation: 17114,
    stPopulation: 1532,
    scPercent: 19.29,
    stPercent: 1.73,
    literacy: 53.7,
    area: 360,
    density: 247,
  },
  {
    name: "Peapully",
    slug: "peapully",
    villages: 19,
    gramPanchayats: 26,
    population: 73692,
    male: 37613,
    female: 36079,
    households: 16607,
    sexRatio: 960,
    scPopulation: 9854,
    stPopulation: 3102,
    scPercent: 13.37,
    stPercent: 4.21,
    literacy: 48.73,
    area: 548,
    density: 134,
  },
];

export const CONSTITUENCY_TOTALS = {
  mandals: 3,
  totalVillages: MANDALS.reduce((s, m) => s + m.villages, 0),
  totalGPs: MANDALS.reduce((s, m) => s + m.gramPanchayats, 0),
  totalPopulation: MANDALS.reduce((s, m) => s + m.population, 0),
  totalMale: MANDALS.reduce((s, m) => s + m.male, 0),
  totalFemale: MANDALS.reduce((s, m) => s + m.female, 0),
  totalHouseholds: MANDALS.reduce((s, m) => s + m.households, 0),
  totalSC: MANDALS.reduce((s, m) => s + m.scPopulation, 0),
  totalST: MANDALS.reduce((s, m) => s + m.stPopulation, 0),
  get sexRatio() {
    return Math.round((this.totalFemale / this.totalMale) * 1000);
  },
  get scPercent() {
    return +((this.totalSC / this.totalPopulation) * 100).toFixed(2);
  },
  get stPercent() {
    return +((this.totalST / this.totalPopulation) * 100).toFixed(2);
  },
};

/* ── Voter demographics ──────────────────────────────────── */

export const VOTER_DEMOGRAPHICS = {
  totalVoters: 227835,
  maleVoters: 113204,
  femaleVoters: 114588,
  thirdGender: 43,
  urbanPercent: 34.77,
  ruralPercent: 65.23,
  scPercent: 15.42,
  stPercent: 2.72,
  turnout2024: 83.54,
  votesPolled2024: 190320,
} as const;

/* ── Elections ───────────────────────────────────────────── */

export type ElectionResult = {
  year: number;
  winner: string;
  winnerParty: string;
  winnerVotes?: number;
  runnerUp?: string;
  runnerUpParty?: string;
  runnerUpVotes?: number;
  margin: number;
  registeredVoters?: number;
  turnout?: number;
  votesPolled?: number;
  note?: string;
};

export const ELECTION_2024: ElectionResult = {
  year: 2024,
  winner: "Kotla Jayasurya Prakasha Reddy",
  winnerParty: "TDP (NDA)",
  winnerVotes: 93523,
  runnerUp: "Buggana Raja Reddy",
  runnerUpParty: "YSRCP",
  runnerUpVotes: 87474,
  margin: 6049,
  registeredVoters: 227835,
  turnout: 83.54,
  votesPolled: 190320,
};

export const ELECTION_HISTORY: ElectionResult[] = [
  ELECTION_2024,
  {
    year: 2019,
    winner: "Buggana Raja Reddy",
    winnerParty: "YSRCP",
    winnerVotes: 109688,
    runnerUp: "Kotla Jayasurya Prakasha Reddy",
    runnerUpParty: "TDP",
    runnerUpVotes: 74172,
    margin: 35516,
    registeredVoters: 217432,
    turnout: 85.12,
    votesPolled: 185078,
  },
  {
    year: 2014,
    winner: "Buggana Rajendranath Reddy",
    winnerParty: "YSRCP",
    margin: 0,
    note: "Later served as Finance Minister of Andhra Pradesh",
  },
  {
    year: 2009,
    winner: "Kambalapadu Ediga Krishna Murthy",
    winnerParty: "TDP",
    margin: 0,
  },
];

/* ── Polling stations ────────────────────────────────────── */

export type PollingStation = { part: number; name: string };

export const POLLING_STATIONS: PollingStation[] = [
  { part: 1, name: "Chanugondla" },
  { part: 2, name: "Chanugondla" },
  { part: 3, name: "Chanugondla" },
  { part: 4, name: "Indirampalli" },
  { part: 5, name: "B Ramadurgam" },
  { part: 6, name: "Eddupenta" },
  { part: 7, name: "Taaduru" },
  { part: 8, name: "Middepalli" },
  { part: 9, name: "Anumpalli" },
  { part: 10, name: "Sh Gundala" },
  { part: 11, name: "Kottaburuju" },
  { part: 12, name: "Tiruanampalli" },
  { part: 13, name: "Kotrai" },
  { part: 14, name: "Pedda Podilla" },
  { part: 15, name: "Pedda Podilla" },
  { part: 16, name: "Chinna Puddhella" },
  { part: 17, name: "Chinna Podilla" },
  { part: 18, name: "Kalachatla" },
  { part: 19, name: "Kalachatla" },
  { part: 20, name: "Kalachatla" },
  { part: 21, name: "Sh Rangapuram" },
  { part: 22, name: "Potudoddi" },
  { part: 23, name: "Potudoddi" },
  { part: 24, name: "Mandoddi" },
  { part: 25, name: "Pyapili" },
  { part: 26, name: "Peapully" },
  { part: 27, name: "Pyapili" },
  { part: 28, name: "Peapully" },
  { part: 29, name: "Pyapili" },
  { part: 30, name: "Pyapili" },
  { part: 31, name: "Pyapili" },
  { part: 32, name: "Pyapili" },
  { part: 33, name: "Pyapili" },
  { part: 34, name: "Peapully" },
  { part: 35, name: "Pyapili" },
  { part: 36, name: "Yerra Pattelu" },
  { part: 37, name: "Yerra Pattalu" },
  { part: 38, name: "Pyapili" },
  { part: 39, name: "Peapully" },
  { part: 40, name: "Pyapili" },
  { part: 41, name: "Peapully" },
  { part: 42, name: "Pyapili" },
  { part: 43, name: "Pyapili" },
  { part: 44, name: "Obuladevarapalli" },
  { part: 45, name: "Mettu Palli" },
  { part: 46, name: "Mettupalli" },
  { part: 47, name: "Enugu Marri" },
  { part: 48, name: "N Rangapuram" },
  { part: 49, name: "Venkatam Palli" },
  { part: 50, name: "Kothakota" },
  { part: 51, name: "Kothakota" },
  { part: 52, name: "Nakkavagulapalli" },
  { part: 53, name: "Devarabanda" },
  { part: 54, name: "Devarabanda" },
  { part: 55, name: "Obula Puram" },
  { part: 56, name: "U Kotha Palli" },
  { part: 57, name: "U Kotha Palli" },
  { part: 58, name: "Ungaranigundla" },
  { part: 59, name: "Seasam Guntala" },
  { part: 60, name: "Yapadinne" },
  { part: 61, name: "Malyala" },
  { part: 62, name: "Gumma Konda" },
  { part: 63, name: "Gumma Konda" },
  { part: 64, name: "Venkata Puram" },
  { part: 65, name: "Abbireddy Palli" },
  { part: 66, name: "Mallempalli" },
  { part: 67, name: "Lakshmipalli" },
  { part: 68, name: "Bonthiralla" },
  { part: 69, name: "Jagadurthy" },
  { part: 70, name: "T M Kothuru" },
  { part: 71, name: "Udumulapadu" },
  { part: 72, name: "Udumulapadu" },
  { part: 73, name: "Kamaganikuntla" },
  { part: 74, name: "Thimmapuram" },
  { part: 75, name: "Somapuram" },
  { part: 76, name: "Avuladoddi" },
  { part: 77, name: "Dhone" },
  { part: 78, name: "Dhone" },
  { part: 79, name: "Dhone" },
  { part: 80, name: "Dhone" },
  { part: 81, name: "Dhone" },
  { part: 82, name: "Dhone" },
  { part: 83, name: "Dhone" },
  { part: 84, name: "Dhone" },
  { part: 85, name: "Dhone" },
  { part: 86, name: "Dhone" },
  { part: 87, name: "Dhone" },
  { part: 88, name: "Dhone" },
  { part: 89, name: "Dhone" },
  { part: 90, name: "Dhone" },
  { part: 91, name: "Dhone" },
  { part: 92, name: "Dhone" },
  { part: 93, name: "Dhone" },
  { part: 94, name: "Dhone" },
  { part: 95, name: "Dhone" },
  { part: 96, name: "Dhone" },
  { part: 97, name: "Dhone" },
  { part: 98, name: "Dhone" },
  { part: 99, name: "Dhone" },
  { part: 100, name: "Dhone" },
  { part: 101, name: "Dhone" },
  { part: 102, name: "Dhone" },
  { part: 103, name: "Dhone Urban" },
  { part: 104, name: "Dhone" },
  { part: 105, name: "Dhone" },
  { part: 106, name: "Dhone" },
  { part: 107, name: "Dhone" },
  { part: 108, name: "Dhone" },
  { part: 109, name: "Dhone" },
  { part: 110, name: "Dhone Urban" },
  { part: 111, name: "Dhone" },
  { part: 112, name: "Dhone" },
  { part: 113, name: "Dhone" },
  { part: 114, name: "Dhone" },
  { part: 115, name: "Dhone" },
  { part: 116, name: "Dhone" },
  { part: 117, name: "Dhone" },
  { part: 118, name: "Dhone" },
  { part: 119, name: "Dhone" },
  { part: 120, name: "Dhone" },
  { part: 121, name: "Dhone" },
  { part: 122, name: "Dhone" },
  { part: 123, name: "Dhone" },
  { part: 124, name: "Dhone" },
  { part: 125, name: "Dhone" },
  { part: 126, name: "Dhone" },
  { part: 127, name: "Dhone" },
  { part: 128, name: "Dhone" },
  { part: 129, name: "Dhone" },
  { part: 130, name: "Dhone" },
  { part: 131, name: "Dhone" },
  { part: 132, name: "Dhone" },
  { part: 133, name: "Dhone" },
  { part: 134, name: "Dhone" },
  { part: 135, name: "Dorapalli" },
  { part: 136, name: "Dorapalli" },
  { part: 137, name: "Dorapalli" },
  { part: 138, name: "Venkata Nayani Palli" },
  { part: 139, name: "Venkata Nayani Palli" },
  { part: 140, name: "Gosani Palli" },
  { part: 141, name: "Gosanipalli" },
  { part: 142, name: "Darmavaram" },
  { part: 143, name: "Darmavaram" },
  { part: 144, name: "Darmavaram" },
  { part: 145, name: "Erraguntla" },
  { part: 146, name: "Erraguntla" },
  { part: 147, name: "Kocheruvu" },
  { part: 148, name: "Kocheruvu" },
  { part: 149, name: "Kocheruvu" },
  { part: 150, name: "Kocheruvu" },
  { part: 151, name: "Chintalapeta" },
  { part: 152, name: "Kannapakunta" },
  { part: 153, name: "Ramakrishnapuram" },
  { part: 154, name: "Jala Durgam" },
  { part: 155, name: "Jala Durgam" },
  { part: 156, name: "Jala Durgam" },
  { part: 157, name: "Jaladurgam" },
  { part: 158, name: "Jala Durgam" },
  { part: 159, name: "Jaladurgam" },
  { part: 160, name: "Uta Konda" },
  { part: 161, name: "Uttakonda" },
  { part: 162, name: "Gopala Nagaram" },
  { part: 163, name: "Kommemarri" },
  { part: 164, name: "Siddanagattu" },
  { part: 165, name: "Hussainapuram" },
  { part: 166, name: "Hussainapuram" },
  { part: 167, name: "Bavi Palli" },
  { part: 168, name: "Bavipalli" },
  { part: 169, name: "Chandra Palli" },
  { part: 170, name: "Chandra Palli" },
  { part: 171, name: "Venkata Kondapuram" },
  { part: 172, name: "Gudipadu" },
  { part: 173, name: "Gudipadu" },
  { part: 174, name: "P. R. Palli" },
  { part: 175, name: "P.R.Palli" },
  { part: 176, name: "Nallamekalapalli" },
  { part: 177, name: "D Rangapuram" },
  { part: 178, name: "Nallamekala Palli" },
  { part: 179, name: "Jakkasanikuntla" },
  { part: 180, name: "Rachavandla Palli" },
  { part: 181, name: "Mamillapalli" },
  { part: 182, name: "Burugula" },
  { part: 183, name: "Seethamma Tanda" },
  { part: 184, name: "Burugula" },
  { part: 185, name: "Burugula" },
  { part: 186, name: "Kowlupalli" },
  { part: 187, name: "Neredu Charla" },
  { part: 188, name: "Neredu Charla" },
  { part: 189, name: "Racharla" },
  { part: 190, name: "Racharla" },
  { part: 191, name: "Boina Cheruvupalli" },
  { part: 192, name: "Boyecheruvu Palli" },
  { part: 193, name: "Muni Madugu" },
  { part: 194, name: "Alebad" },
  { part: 195, name: "Madhavaram" },
  { part: 196, name: "Garladinne" },
  { part: 197, name: "Garladinne" },
  { part: 198, name: "Chinna Malkapuram" },
  { part: 199, name: "Chinna Malkapuram" },
  { part: 200, name: "Chinna Malkapuram" },
  { part: 201, name: "Chinna Malkapuram" },
  { part: 202, name: "S Valasala" },
  { part: 203, name: "Pedda Malkapuram" },
  { part: 204, name: "Kamalapuram" },
  { part: 205, name: "Kamalapuram" },
  { part: 206, name: "R Kotha Palli" },
  { part: 207, name: "R.Kothapalli" },
  { part: 208, name: "Bukkapuram" },
  { part: 209, name: "Ambhapuram" },
  { part: 210, name: "Ambapuram" },
  { part: 211, name: "R S Rangapuram" },
  { part: 212, name: "R S Rangapuram" },
  { part: 213, name: "R S Rangapuram" },
  { part: 214, name: "R.S.Rangapuram" },
  { part: 215, name: "R S Rangapuram" },
  { part: 216, name: "R S Rangapuram" },
  { part: 217, name: "K R Kottala" },
  { part: 218, name: "Gutupalli" },
  { part: 219, name: "Gutu Palli" },
  { part: 220, name: "Rahimanpuram" },
  { part: 221, name: "Nagamallakunta" },
  { part: 222, name: "Hussainapuram" },
  { part: 223, name: "Kolumula Palli" },
  { part: 224, name: "Kolumula Palli" },
  { part: 225, name: "Kolumula Palli" },
  { part: 226, name: "Balapala Palli" },
  { part: 227, name: "Balapala Palli" },
  { part: 228, name: "Seetharamapuram" },
  { part: 229, name: "Seetharamapuram" },
  { part: 230, name: "Muddavaram" },
  { part: 231, name: "M P P School" },
  { part: 232, name: "Veeraipalli" },
  { part: 233, name: "Musali Cheruvu" },
  { part: 234, name: "M Pendekal" },
  { part: 235, name: "Marrikunta" },
  { part: 236, name: "Venkatagiri" },
  { part: 237, name: "Repalli" },
  { part: 238, name: "Embai" },
  { part: 239, name: "Rudravaram" },
  { part: 240, name: "Mandlavanipalli" },
  { part: 241, name: "Sankalapuram" },
  { part: 242, name: "Boinapalli" },
  { part: 243, name: "Buggani Palli" },
  { part: 244, name: "Buggani Palli" },
  { part: 245, name: "Bugganipalle" },
  { part: 246, name: "Bugganipalli Tanda" },
  { part: 247, name: "Gorumanukonda" },
  { part: 248, name: "Gorumanukonda Tanda" },
  { part: 249, name: "Cement Nagar" },
  { part: 250, name: "Cement Nagar" },
  { part: 251, name: "Cement Nagar" },
  { part: 252, name: "Cement Nagar" },
  { part: 253, name: "Cement Nagar" },
  { part: 254, name: "Cement Nagar" },
  { part: 255, name: "Cement Nagar" },
  { part: 256, name: "Betamcherla" },
  { part: 257, name: "Betamcherla" },
  { part: 258, name: "Betamcherla" },
  { part: 259, name: "Betamcherla" },
  { part: 260, name: "Betamcherla" },
  { part: 261, name: "Betamcherla" },
  { part: 262, name: "Bethamcherla" },
  { part: 263, name: "Betamcherla" },
  { part: 264, name: "Betamcherla" },
  { part: 265, name: "Betamcherla" },
  { part: 266, name: "Betamcherla" },
  { part: 267, name: "Bethancherla" },
  { part: 268, name: "Bethancherla" },
  { part: 269, name: "Bethancherla" },
  { part: 270, name: "Bethancherla" },
  { part: 271, name: "Bethancherla" },
  { part: 272, name: "Bethancherla" },
  { part: 273, name: "Bethancherla" },
  { part: 274, name: "Bethancherla" },
  { part: 275, name: "Bethancherla" },
  { part: 276, name: "Bethancherla" },
  { part: 277, name: "Bethancherla" },
  { part: 278, name: "Bethancherla" },
  { part: 279, name: "Bethancherla" },
  { part: 280, name: "Bethancherla" },
  { part: 281, name: "Bethamcherla" },
  { part: 282, name: "Betamcherla" },
  { part: 283, name: "Bethamcherla" },
  { part: 284, name: "Bethamcherla" },
  { part: 285, name: "Bethamcherla" },
  { part: 286, name: "Betamcherla" },
  { part: 287, name: "H K Kottala" },
  { part: 288, name: "H K Kottala" },
  { part: 289, name: "K K Kottala" },
  { part: 290, name: "Gorlagutta" },
  { part: 291, name: "Gorlagutta" },
];

/* ── Booth-to-Village mapping ────────────────────────────── */

// Maps polling station names (lowercase, normalized) to village_name in villages.ts
// Booths that don't match a census village are mapped to their nearest parent village or town
export const BOOTH_VILLAGE_MAP: Record<string, string> = {
  "chanugondla": "Chanugondla",
  "indirampalli": "Chanugondla",
  "b ramadurgam": "Eddupenta",
  "eddupenta": "Eddupenta",
  "taaduru": "Eddupenta",
  "middepalli": "Eddupenta",
  "anumpalli": "Eddupenta",
  "sh gundala": "Shotrium Gundala",
  "kottaburuju": "Kotha Buruju",
  "tiruanampalli": "Kotha Buruju",
  "kotrai": "Kotha Buruju",
  "pedda podilla": "Peddapodilla",
  "chinna puddhella": "Peddapodilla",
  "chinna podilla": "Peddapodilla",
  "kalachatla": "Kalachetla",
  "sh rangapuram": "Shrotrium Rangapuram",
  "potudoddi": "Pothidoddi",
  "mandoddi": "Pothidoddi",
  "pyapili": "Peapally",
  "peapully": "Peapally",
  "yerra pattelu": "Peapally",
  "yerra pattalu": "Peapally",
  "obuladevarapalli": "Peapally",
  "mettu palli": "Mettupalle",
  "mettupalli": "Mettupalle",
  "enugu marri": "Mettupalle",
  "n rangapuram": "Mettupalle",
  "venkatam palli": "Venkatapuram",
  "kothakota": "Kothakota",
  "nakkavagulapalli": "Kothakota",
  "devarabanda": "Devarabanda",
  "obula puram": "Devarabanda",
  "u kotha palli": "Devarabanda",
  "ungaranigundla": "Ungaranigundla",
  "seasam guntala": "Ungaranigundla",
  "yapadinne": "Yapadinne",
  "malyala": "Yapadinne",
  "gumma konda": "Venkatapuram",
  "venkata puram": "Venkatapuram",
  "abbireddy palli": "Venkatapuram",
  "mallempalli": "Malkapuram",
  "lakshmipalli": "Malkapuram",
  "bonthiralla": "Malkapuram",
  "jagadurthy": "Jagadurthi",
  "t m kothuru": "Jagadurthi",
  "udumulapadu": "Udumulapadu",
  "kamaganikuntla": "Kamaganikuntla",
  "thimmapuram": "Kamaganikuntla",
  "somapuram": "Kamaganikuntla",
  "avuladoddi": "Kamaganikuntla",
  "dhone": "Dhone (R)",
  "dhone urban": "Dhone (R)",
  "dorapalli": "Dhone (R)",
  "venkata nayani palli": "Dhone (R)",
  "gosani palli": "Dhone (R)",
  "gosanipalli": "Dhone (R)",
  "darmavaram": "Dhone (R)",
  "erraguntla": "Kocheruvu",
  "kocheruvu": "Kocheruvu",
  "chintalapeta": "Kocheruvu",
  "kannapakunta": "Kocheruvu",
  "ramakrishnapuram": "Jaladurgam",
  "jala durgam": "Jaladurgam",
  "jaladurgam": "Jaladurgam",
  "uta konda": "Jaladurgam",
  "uttakonda": "Jaladurgam",
  "gopala nagaram": "Kommemarri",
  "kommemarri": "Kommemarri",
  "siddanagattu": "Kommemarri",
  "hussainapuram": "Kommemarri",
  "bavi palli": "Chandrapalle",
  "bavipalli": "Chandrapalle",
  "chandra palli": "Chandrapalle",
  "venkata kondapuram": "Gudipadu",
  "gudipadu": "Gudipadu",
  "p. r. palli": "Gudipadu",
  "p.r.palli": "Gudipadu",
  "nallamekalapalli": "Jakkasanikuntla",
  "d rangapuram": "Jakkasanikuntla",
  "nallamekala palli": "Jakkasanikuntla",
  "jakkasanikuntla": "Jakkasanikuntla",
  "rachavandla palli": "Racherla",
  "mamillapalli": "Racherla",
  "burugula": "Burugula",
  "seethamma tanda": "Burugula",
  "kowlupalli": "Burugula",
  "neredu charla": "Nereducherla",
  "racharla": "Racherla",
  "boina cheruvupalli": "Racherla",
  "boyecheruvu palli": "Racherla",
  "muni madugu": "Munimadugu",
  "alebad": "Munimadugu",
  "madhavaram": "Madhavaram",
  "garladinne": "Madhavaram",
  "chinna malkapuram": "Malkapuram",
  "s valasala": "Shotrium Valasala",
  "pedda malkapuram": "Malkapuram",
  "kamalapuram": "Malkapuram",
  "r kotha palli": "Kothapalle",
  "r.kothapalli": "Kothapalle",
  "bukkapuram": "Kothapalle",
  "ambhapuram": "Ambapuram",
  "ambapuram": "Ambapuram",
  "r s rangapuram": "Rangapuram",
  "r.s.rangapuram": "Rangapuram",
  "k r kottala": "Rangapuram",
  "gutu palli": "Gutupalle",
  "gutupalli": "Gutupalle",
  "rahimanpuram": "Gutupalle",
  "nagamallakunta": "Gutupalle",
  "kolumula palli": "Kolumulapalle",
  "balapala palli": "Kolumulapalle",
  "seetharamapuram": "Kolumulapalle",
  "muddavaram": "Muddavaram",
  "m p p school": "Muddavaram",
  "veeraipalli": "Muddavaram",
  "musali cheruvu": "Pendakal",
  "m pendekal": "Pendakal",
  "marrikunta": "Pendakal",
  "venkatagiri": "Pendakal",
  "repalli": "Pendakal",
  "embai": "Emboy",
  "rudravaram": "Emboy",
  "mandlavanipalli": "Emboy",
  "sankalapuram": "Emboy",
  "boinapalli": "Bugganipalle",
  "buggani palli": "Bugganipalle",
  "bugganipalle": "Bugganipalle",
  "bugganipalli tanda": "Bugganipalle",
  "gorumanukonda": "Bugganipalle",
  "gorumanukonda tanda": "Bugganipalle",
  "cement nagar": "Gollagutta",
  "betamcherla": "Rangapuram",
  "bethamcherla": "Rangapuram",
  "bethancherla": "Rangapuram",
  "h k kottala": "Rangapuram",
  "k k kottala": "Rangapuram",
  "gorlagutta": "Gollagutta",
  "vengalampalli": "Vengalampalle",
  "shrotrium nallaballe": "Shrotrium Nallaballe",
  "shrotrium rayampeta": "Shrotrium Rayampeta",
};

export function getBoothsForVillage(villageName: string): { part: number; name: string }[] {
  return POLLING_STATIONS.filter((s) => {
    const mapped = BOOTH_VILLAGE_MAP[s.name.toLowerCase()];
    return mapped === villageName;
  });
}

export function getBoothCountByVillage(): Map<string, number> {
  const counts = new Map<string, number>();
  for (const s of POLLING_STATIONS) {
    const village = BOOTH_VILLAGE_MAP[s.name.toLowerCase()];
    if (village) counts.set(village, (counts.get(village) ?? 0) + 1);
  }
  return counts;
}

/* ── Electoral roll years ────────────────────────────────── */

export const AVAILABLE_ROLLS = [
  { year: 2026, rolls: ["SIR Draft Roll"] },
  { year: 2025, rolls: ["Final Roll", "Draft Roll", "Supplement-4"] },
  { year: 2024, rolls: ["General Election Roll"] },
];

/* ── Gram Panchayats per mandal (from nandyal.ap.gov.in) ── */

export const GRAM_PANCHAYATS: Record<string, string[]> = {
  dhone: [
    "Avuladoddi", "Ch.Malkapuram", "Chanugondla", "Devarabanda", "Dharmavaram",
    "Dorapalli", "Gosanipalli", "Gummakonda", "Jagadurthy", "Kamaganikuntla",
    "Kamalapuram", "Kannapukunta", "Kocheruvu", "Kothaburuju", "Kothakota",
    "Kotrai", "Mallempalli", "U.Kothapalli", "Udumulapadu", "Ungaranigundla",
    "Vekatanayunipalli", "Venkatapuram", "Yapadinne", "Yarraguntla", "Yeddupenta",
  ],
  bethamcherla: [
    "Ambapuram", "Bethemcherla", "Bugganipalli", "Bukkapuram", "Cement Nagar",
    "Emboy", "Gorlagutta", "Gorumankonda", "Gutupalli", "H.Kottala",
    "K.K.Kottala", "Kolumulapalli", "M.Pendekal", "Muddavaram", "R.Kothapalli",
    "R.S.Rangapuram", "Rahimanpuram", "Sankalapuram", "Seetharamapuram", "Thavisikonda",
  ],
  peapully: [
    "Bavipalli", "Boyenacherupalli", "Burugula", "Chardrapalli", "Chinnapodilla",
    "Gudipadu", "Hussinapuram", "Jakkasanikuntla", "Jaladurgam", "Kalachatla",
    "Kommemari", "Koulupalli", "Madhavaram", "Mettupalli", "Munimadugu",
    "N.Rangapuram", "Nereducherla", "P.R.Palli", "Peapully", "Peddapaya",
    "Peddapoddella", "Pothudoddi", "Racherla", "Utakonda", "Vengalampalli",
    "Yenugumarri",
  ],
};
