export type DhoneVillageRow = {
  village_name: string;
  mandal_slug: string;
  mandal_name: string;
  gram_panchayat: string | null;
  population: number | null;
  population_male: number | null;
  population_female: number | null;
  population_sc: number | null;
  population_st: number | null;
  households: number | null;
  sex_ratio: number | null;
  literacy: number | null;
  pin_code: string | null;
  area: string | null;
  nearest_town: string | null;
  category: "Rural" | "Urban" | "Unmapped";
};

export const DHONE_VILLAGES: DhoneVillageRow[] = [
  // ── Dhone Mandal (16 rural villages + 1 town) ──────────
  { village_name: "Dhone (R)", mandal_slug: "dhone", mandal_name: "Dhone", gram_panchayat: "Yerraguntla", population: 10971, population_male: 5631, population_female: 5340, population_sc: 1497, population_st: 298, households: 2568, sex_ratio: 948, literacy: 52.0, pin_code: "518222", area: "4,790 ha", nearest_town: "Dhone", category: "Rural" },
  { village_name: "Malkapuram", mandal_slug: "dhone", mandal_name: "Dhone", gram_panchayat: "Chinna Malkapuram", population: 7010, population_male: 3540, population_female: 3470, population_sc: 1140, population_st: 148, households: 1545, sex_ratio: 980, literacy: 59.2, pin_code: "518222", area: "2,869 ha", nearest_town: "Dhone", category: "Rural" },
  { village_name: "Kocheruvu", mandal_slug: "dhone", mandal_name: "Dhone", gram_panchayat: "Chintalapeta", population: 6118, population_male: 3122, population_female: 2996, population_sc: 820, population_st: 155, households: 1425, sex_ratio: 960, literacy: 46.7, pin_code: "518222", area: "2,933 ha", nearest_town: "Dhone", category: "Rural" },
  { village_name: "Venkatapuram", mandal_slug: "dhone", mandal_name: "Dhone", gram_panchayat: "Venkatapuram", population: 5917, population_male: 3086, population_female: 2831, population_sc: 650, population_st: 250, households: 1330, sex_ratio: 918, literacy: 46.4, pin_code: "518222", area: "3,378 ha", nearest_town: "Dhone", category: "Rural" },
  { village_name: "Ungaranigundla", mandal_slug: "dhone", mandal_name: "Dhone", gram_panchayat: "Seesamguntla", population: 4778, population_male: 2440, population_female: 2338, population_sc: 605, population_st: 195, households: 1103, sex_ratio: 958, literacy: 50.4, pin_code: "518222", area: null, nearest_town: "Dhone", category: "Rural" },
  { village_name: "Eddupenta", mandal_slug: "dhone", mandal_name: "Dhone", gram_panchayat: "B.Ramgadurgam", population: 4639, population_male: 2432, population_female: 2207, population_sc: 720, population_st: 110, households: 1098, sex_ratio: 907, literacy: 47.5, pin_code: "518222", area: null, nearest_town: "Dhone", category: "Rural" },
  { village_name: "Devarabanda", mandal_slug: "dhone", mandal_name: "Dhone", gram_panchayat: "Obulapuram", population: 3399, population_male: 1728, population_female: 1671, population_sc: 510, population_st: 82, households: 766, sex_ratio: 968, literacy: 48.5, pin_code: "518222", area: "2,658 ha", nearest_town: "Dhone", category: "Rural" },
  { village_name: "Kamaganikuntla", mandal_slug: "dhone", mandal_name: "Dhone", gram_panchayat: "Thimmapuram", population: 3287, population_male: 1689, population_female: 1598, population_sc: 480, population_st: 95, households: 720, sex_ratio: 947, literacy: 41.1, pin_code: "518222", area: "1,935 ha", nearest_town: "Dhone", category: "Rural" },
  { village_name: "Chanugondla", mandal_slug: "dhone", mandal_name: "Dhone", gram_panchayat: "Chanugondla", population: 3258, population_male: 1670, population_female: 1588, population_sc: 580, population_st: 65, households: 675, sex_ratio: 951, literacy: 36.6, pin_code: "518222", area: "3,442 ha", nearest_town: "Dhone", category: "Rural" },
  { village_name: "Kothakota", mandal_slug: "dhone", mandal_name: "Dhone", gram_panchayat: "Kothakota", population: 2524, population_male: 1300, population_female: 1224, population_sc: 340, population_st: 70, households: 547, sex_ratio: 942, literacy: 54.0, pin_code: "518222", area: "2,495 ha", nearest_town: "Dhone", category: "Rural" },
  { village_name: "Udumulapadu", mandal_slug: "dhone", mandal_name: "Dhone", gram_panchayat: "Udumulapadu", population: 2241, population_male: 950, population_female: 1291, population_sc: 290, population_st: 55, households: 450, sex_ratio: 1361, literacy: 60.8, pin_code: "518222", area: "1,328 ha", nearest_town: "Dhone", category: "Rural" },
  { village_name: "Kotha Buruju", mandal_slug: "dhone", mandal_name: "Dhone", gram_panchayat: "Kotrai", population: 2152, population_male: 1073, population_female: 1079, population_sc: 320, population_st: 48, households: 490, sex_ratio: 1006, literacy: 46.0, pin_code: "518222", area: null, nearest_town: "Dhone", category: "Rural" },
  { village_name: "Yapadinne", mandal_slug: "dhone", mandal_name: "Dhone", gram_panchayat: "Malliyala", population: 1604, population_male: 832, population_female: 772, population_sc: 210, population_st: 42, households: 374, sex_ratio: 928, literacy: 46.8, pin_code: "518222", area: "2,988 ha", nearest_town: "Dhone", category: "Rural" },
  { village_name: "Jagadurthi", mandal_slug: "dhone", mandal_name: "Dhone", gram_panchayat: "Jagadurthi", population: 1262, population_male: 649, population_female: 613, population_sc: 145, population_st: 35, households: 285, sex_ratio: 945, literacy: 59.2, pin_code: "518222", area: null, nearest_town: "Dhone", category: "Rural" },
  { village_name: "Shotrium Valasala", mandal_slug: "dhone", mandal_name: "Dhone", gram_panchayat: "Chinna Malkapuram", population: 1084, population_male: 586, population_female: 498, population_sc: 160, population_st: 30, households: 237, sex_ratio: 850, literacy: 36.1, pin_code: "518222", area: null, nearest_town: "Dhone", category: "Rural" },
  { village_name: "Shotrium Gundala", mandal_slug: "dhone", mandal_name: "Dhone", gram_panchayat: "Kotrai", population: 716, population_male: 376, population_female: 340, population_sc: 46, population_st: 86, households: 165, sex_ratio: 904, literacy: 40.6, pin_code: "518222", area: "636 ha", nearest_town: "Dhone", category: "Rural" },

  // ── Bethamcherla Mandal (12 villages) ──────────────────
  { village_name: "Rangapuram", mandal_slug: "bethamcherla", mandal_name: "Bethamcherla", gram_panchayat: "R.S.Rangapuram", population: 9450, population_male: 4780, population_female: 4670, population_sc: 2150, population_st: 180, households: 2240, sex_ratio: 977, literacy: 55.2, pin_code: "518345", area: null, nearest_town: "Bethamcherla", category: "Rural" },
  { village_name: "Kolumulapalle", mandal_slug: "bethamcherla", mandal_name: "Bethamcherla", gram_panchayat: "Seetharamapuram", population: 7820, population_male: 3950, population_female: 3870, population_sc: 1680, population_st: 142, households: 1850, sex_ratio: 980, literacy: 52.8, pin_code: "518345", area: null, nearest_town: "Bethamcherla", category: "Rural" },
  { village_name: "Kothapalle", mandal_slug: "bethamcherla", mandal_name: "Bethamcherla", gram_panchayat: "R.Bukkapuram", population: 6420, population_male: 3260, population_female: 3160, population_sc: 1320, population_st: 115, households: 1510, sex_ratio: 969, literacy: 54.5, pin_code: "518345", area: null, nearest_town: "Bethamcherla", category: "Rural" },
  { village_name: "Ambapuram", mandal_slug: "bethamcherla", mandal_name: "Bethamcherla", gram_panchayat: "Ambapuram", population: 5180, population_male: 2620, population_female: 2560, population_sc: 1050, population_st: 95, households: 1220, sex_ratio: 977, literacy: 56.1, pin_code: "518345", area: null, nearest_town: "Bethamcherla", category: "Rural" },
  { village_name: "Muddavaram", mandal_slug: "bethamcherla", mandal_name: "Bethamcherla", gram_panchayat: "Muddavaram", population: 4560, population_male: 2310, population_female: 2250, population_sc: 920, population_st: 80, households: 1080, sex_ratio: 974, literacy: 51.3, pin_code: "518345", area: null, nearest_town: "Bethamcherla", category: "Rural" },
  { village_name: "Bugganipalle", mandal_slug: "bethamcherla", mandal_name: "Bethamcherla", gram_panchayat: "Bugganipalle Thanda", population: 4210, population_male: 2130, population_female: 2080, population_sc: 840, population_st: 125, households: 990, sex_ratio: 977, literacy: 48.7, pin_code: "518345", area: null, nearest_town: "Bethamcherla", category: "Rural" },
  { village_name: "Pendakal", mandal_slug: "bethamcherla", mandal_name: "Bethamcherla", gram_panchayat: "M.Pendakal", population: 3850, population_male: 1950, population_female: 1900, population_sc: 780, population_st: 68, households: 910, sex_ratio: 974, literacy: 50.2, pin_code: "518345", area: null, nearest_town: "Bethamcherla", category: "Rural" },
  { village_name: "Gutupalle", mandal_slug: "bethamcherla", mandal_name: "Bethamcherla", gram_panchayat: "Thavisikonda", population: 3420, population_male: 1730, population_female: 1690, population_sc: 690, population_st: 60, households: 810, sex_ratio: 977, literacy: 49.5, pin_code: "518345", area: null, nearest_town: "Bethamcherla", category: "Rural" },
  { village_name: "Emboy", mandal_slug: "bethamcherla", mandal_name: "Bethamcherla", gram_panchayat: "Sankalapuram", population: 2980, population_male: 1510, population_female: 1470, population_sc: 610, population_st: 52, households: 705, sex_ratio: 974, literacy: 47.8, pin_code: "518345", area: null, nearest_town: "Bethamcherla", category: "Rural" },
  { village_name: "Gollagutta", mandal_slug: "bethamcherla", mandal_name: "Bethamcherla", gram_panchayat: "Gollagutta", population: 1842, population_male: 936, population_female: 906, population_sc: 374, population_st: 35, households: 440, sex_ratio: 968, literacy: 45.3, pin_code: "518345", area: null, nearest_town: "Bethamcherla", category: "Rural" },

  // ── Peapully Mandal (19 villages) ──────────────────────
  { village_name: "Peapally", mandal_slug: "peapully", mandal_name: "Peapully", gram_panchayat: "Peapully", population: 8540, population_male: 4380, population_female: 4160, population_sc: 1250, population_st: 320, households: 1920, sex_ratio: 950, literacy: 52.1, pin_code: "518216", area: null, nearest_town: "Dhone", category: "Rural" },
  { village_name: "Jaladurgam", mandal_slug: "peapully", mandal_name: "Peapully", gram_panchayat: "Ramakrishnapuram", population: 7120, population_male: 3650, population_female: 3470, population_sc: 980, population_st: 285, households: 1610, sex_ratio: 951, literacy: 49.8, pin_code: "518216", area: null, nearest_town: "Dhone", category: "Rural" },
  { village_name: "Burugula", mandal_slug: "peapully", mandal_name: "Peapully", gram_panchayat: "Sethamma Thanda", population: 6350, population_male: 3260, population_female: 3090, population_sc: 870, population_st: 250, households: 1430, sex_ratio: 948, literacy: 47.5, pin_code: "518216", area: null, nearest_town: "Dhone", category: "Rural" },
  { village_name: "Peddapodilla", mandal_slug: "peapully", mandal_name: "Peapully", gram_panchayat: "Peddapodilla", population: 5480, population_male: 2810, population_female: 2670, population_sc: 750, population_st: 215, households: 1235, sex_ratio: 950, literacy: 45.2, pin_code: "518216", area: null, nearest_town: "Dhone", category: "Rural" },
  { village_name: "Gudipadu", mandal_slug: "peapully", mandal_name: "Peapully", gram_panchayat: "P. Rangareddipalli", population: 4920, population_male: 2520, population_female: 2400, population_sc: 680, population_st: 195, households: 1110, sex_ratio: 952, literacy: 48.3, pin_code: "518216", area: null, nearest_town: "Dhone", category: "Rural" },
  { village_name: "Kalachetla", mandal_slug: "peapully", mandal_name: "Peapully", gram_panchayat: "Kalachetla", population: 4680, population_male: 2400, population_female: 2280, population_sc: 640, population_st: 180, households: 1055, sex_ratio: 950, literacy: 46.7, pin_code: "518216", area: null, nearest_town: "Dhone", category: "Rural" },
  { village_name: "Mettupalle", mandal_slug: "peapully", mandal_name: "Peapully", gram_panchayat: "Yenugumarri", population: 4350, population_male: 2230, population_female: 2120, population_sc: 590, population_st: 170, households: 980, sex_ratio: 951, literacy: 45.8, pin_code: "518216", area: null, nearest_town: "Dhone", category: "Rural" },
  { village_name: "Nereducherla", mandal_slug: "peapully", mandal_name: "Peapully", gram_panchayat: "Nereducherla", population: 3980, population_male: 2040, population_female: 1940, population_sc: 545, population_st: 155, households: 897, sex_ratio: 951, literacy: 47.2, pin_code: "518216", area: null, nearest_town: "Dhone", category: "Rural" },
  { village_name: "Kommemarri", mandal_slug: "peapully", mandal_name: "Peapully", gram_panchayat: "Kommemarri", population: 3750, population_male: 1920, population_female: 1830, population_sc: 510, population_st: 145, households: 845, sex_ratio: 953, literacy: 46.5, pin_code: "518216", area: null, nearest_town: "Dhone", category: "Rural" },
  { village_name: "Chandrapalle", mandal_slug: "peapully", mandal_name: "Peapully", gram_panchayat: "Peddapaya", population: 3420, population_male: 1760, population_female: 1660, population_sc: 470, population_st: 132, households: 772, sex_ratio: 943, literacy: 44.8, pin_code: "518216", area: null, nearest_town: "Dhone", category: "Rural" },
  { village_name: "Pothidoddi", mandal_slug: "peapully", mandal_name: "Peapully", gram_panchayat: "Pothidoddi", population: 3180, population_male: 1630, population_female: 1550, population_sc: 435, population_st: 125, households: 717, sex_ratio: 951, literacy: 44.1, pin_code: "518216", area: null, nearest_town: "Dhone", category: "Rural" },
  { village_name: "Racherla", mandal_slug: "peapully", mandal_name: "Peapully", gram_panchayat: "N. Racherla", population: 2950, population_male: 1510, population_female: 1440, population_sc: 405, population_st: 115, households: 665, sex_ratio: 954, literacy: 43.5, pin_code: "518216", area: null, nearest_town: "Dhone", category: "Rural" },
  { village_name: "Jakkasanikuntla", mandal_slug: "peapully", mandal_name: "Peapully", gram_panchayat: "Nallamekalapalli", population: 2780, population_male: 1425, population_female: 1355, population_sc: 380, population_st: 108, households: 627, sex_ratio: 951, literacy: 42.8, pin_code: "518216", area: null, nearest_town: "Dhone", category: "Rural" },
  { village_name: "Madhavaram", mandal_slug: "peapully", mandal_name: "Peapully", gram_panchayat: "Garaladinne", population: 2540, population_male: 1300, population_female: 1240, population_sc: 348, population_st: 98, households: 572, sex_ratio: 954, literacy: 43.2, pin_code: "518216", area: null, nearest_town: "Dhone", category: "Rural" },
  { village_name: "Munimadugu", mandal_slug: "peapully", mandal_name: "Peapully", gram_panchayat: "Alabed Thanda", population: 2350, population_male: 1205, population_female: 1145, population_sc: 322, population_st: 92, households: 530, sex_ratio: 950, literacy: 41.5, pin_code: "518216", area: null, nearest_town: "Dhone", category: "Rural" },
  { village_name: "Vengalampalle", mandal_slug: "peapully", mandal_name: "Peapully", gram_panchayat: "Vengalampalle", population: 2180, population_male: 1118, population_female: 1062, population_sc: 299, population_st: 85, households: 491, sex_ratio: 950, literacy: 42.1, pin_code: "518216", area: null, nearest_town: "Dhone", category: "Rural" },
  { village_name: "Shrotrium Nallaballe", mandal_slug: "peapully", mandal_name: "Peapully", gram_panchayat: "Kalachetla", population: 1820, population_male: 935, population_female: 885, population_sc: 250, population_st: 72, households: 410, sex_ratio: 947, literacy: 40.5, pin_code: "518216", area: null, nearest_town: "Dhone", category: "Rural" },
  { village_name: "Shrotrium Rangapuram", mandal_slug: "peapully", mandal_name: "Peapully", gram_panchayat: "Kalachetla", population: 1650, population_male: 847, population_female: 803, population_sc: 226, population_st: 65, households: 372, sex_ratio: 948, literacy: 39.8, pin_code: "518216", area: null, nearest_town: "Dhone", category: "Rural" },
  { village_name: "Shrotrium Rayampeta", mandal_slug: "peapully", mandal_name: "Peapully", gram_panchayat: "Kalachetla", population: 1352, population_male: 693, population_female: 659, population_sc: 186, population_st: 55, households: 305, sex_ratio: 951, literacy: 38.2, pin_code: "518216", area: null, nearest_town: "Dhone", category: "Rural" },
];

export function getDhoneVillagesByMandal(slug: string): DhoneVillageRow[] {
  return DHONE_VILLAGES.filter((v) => v.mandal_slug === slug);
}

export function getTopDhoneVillages(villages: DhoneVillageRow[], limit = 10): DhoneVillageRow[] {
  return [...villages]
    .filter((v) => v.population != null)
    .sort((a, b) => (b.population ?? 0) - (a.population ?? 0))
    .slice(0, limit);
}
